In [1]:
import tensorflow as tf
import numpy as np
import os
print(os.getcwd())
tfrecordpath = "../Data/tfrecords/"


2025-01-31 18:17:44.667301: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1738343864.676905   47843 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1738343864.679604   47843 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-31 18:17:44.690602: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


/mnt/c/Users/alexs/Desktop/levbot/Training


### Load in data
#### Define schema


In [2]:
def decode(record_bytes):
    # Function for parsing each record in the tf files
    example = tf.io.parse_single_example(
        # Data
        record_bytes,

        # Schema
        {
        'Timeframe': tf.io.FixedLenFeature([], tf.string),
        'timestamp': tf.io.RaggedFeature(dtype=tf.int64),
        'open': tf.io.RaggedFeature(dtype=tf.float32),
        }
        )

    return example

In [3]:
path = tfrecordpath + "BTCUSD_PERP/1m.tfrecord"

dataset1m = tf.data.TFRecordDataset(path,  num_parallel_reads = tf.data.AUTOTUNE)
dataset1m = dataset1m.map(decode, num_parallel_calls = tf.data.AUTOTUNE)

path = tfrecordpath + "BTCUSD_PERP/5m.tfrecord"

dataset5m = tf.data.TFRecordDataset(path,  num_parallel_reads = tf.data.AUTOTUNE)
dataset5m = dataset5m.map(decode, num_parallel_calls = tf.data.AUTOTUNE)



I0000 00:00:1738343867.247585   47843 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5592 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060 Ti, pci bus id: 0000:05:00.0, compute capability: 8.6


In [4]:
for data in dataset1m:
    print(data["timestamp"][0])

2025-01-31 18:17:47.454710: I tensorflow/core/kernels/data/tf_record_dataset_op.cc:370] TFRecordDataset `buffer_size` is unspecified, default to 262144


tf.Tensor(1597129439, shape=(), dtype=int64)


2025-01-31 18:17:47.772184: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [5]:
import TensorSlider


In [6]:
WS = TensorSlider.WindowSlider(30, 10, dataset1m, {"5m": dataset5m})
WS2 = TensorSlider.WindowSlider(30, 10, dataset1m)

In [7]:
for time in WS:
    print(time)
    break
for time in WS2:
    print(time)
    break

{'basetimestamp': <tf.Tensor: shape=(), dtype=int64, numpy=1597138799>}
{'basetimestamp': <tf.Tensor: shape=(), dtype=int64, numpy=1597131239>}


In [8]:
iterate = WS.__iter__()
print(iterate.__next__())
print(iterate.__next__())
print(iterate.__next__())
print(iterate.__next__())
print(iterate.__next__())
print(iterate.__next__())
print(iterate.__next__())
print(iterate.__next__())
print(iterate.__next__())
print(iterate.__next__())

{'basetimestamp': <tf.Tensor: shape=(), dtype=int64, numpy=1597138799>}
{'basetimestamp': <tf.Tensor: shape=(), dtype=int64, numpy=1597138859>}
{'basetimestamp': <tf.Tensor: shape=(), dtype=int64, numpy=1597138919>}
{'basetimestamp': <tf.Tensor: shape=(), dtype=int64, numpy=1597138979>}
{'basetimestamp': <tf.Tensor: shape=(), dtype=int64, numpy=1597139039>}
{'basetimestamp': <tf.Tensor: shape=(), dtype=int64, numpy=1597139099>}
{'basetimestamp': <tf.Tensor: shape=(), dtype=int64, numpy=1597139159>}
{'basetimestamp': <tf.Tensor: shape=(), dtype=int64, numpy=1597139219>}
{'basetimestamp': <tf.Tensor: shape=(), dtype=int64, numpy=1597139279>}
{'basetimestamp': <tf.Tensor: shape=(), dtype=int64, numpy=1597139339>}
