In [1]:
import tensorflow as tf
import numpy as np
import os
print(os.getcwd())
tfrecordpath = "../Data/tfrecords/"


2025-01-31 20:53:56.345593: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-31 20:53:56.354378: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-01-31 20:53:56.365436: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1738353236.383072   15248 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1738353236.387641   15248 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-31 20:53:56.405757: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU ins

/mnt/c/Users/Alexander/PycharmProjects/levbot/Training


### Load in data
#### Define schema


In [2]:
def decode(record_bytes):
    # Function for parsing each record in the tf files
    example = tf.io.parse_single_example(
        # Data
        record_bytes,

        # Schema
        {
        'Timeframe': tf.io.FixedLenFeature([], tf.string),
        'timestamp': tf.io.RaggedFeature(dtype=tf.int64),
        'Open': tf.io.RaggedFeature(dtype=tf.float32),
        'High': tf.io.RaggedFeature(dtype=tf.float32),
        'Low': tf.io.RaggedFeature(dtype=tf.float32),
        'Close': tf.io.RaggedFeature(dtype=tf.float32),
        'Volume': tf.io.RaggedFeature(dtype=tf.float32),
        }
        )

    return example

In [3]:
path = tfrecordpath + "BTCUSD_PERP/1m.tfrecord"

dataset1m = tf.data.TFRecordDataset(path,  num_parallel_reads = tf.data.AUTOTUNE)
dataset1m = dataset1m.map(decode, num_parallel_calls = tf.data.AUTOTUNE)

path = tfrecordpath + "BTCUSD_PERP/5m.tfrecord"

dataset5m = tf.data.TFRecordDataset(path,  num_parallel_reads = tf.data.AUTOTUNE)
dataset5m = dataset5m.map(decode, num_parallel_calls = tf.data.AUTOTUNE)



W0000 00:00:1738353242.027077   15248 gpu_device.cc:2344] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [4]:
for data in dataset1m:
    print(data["timestamp"][0])

2025-01-31 20:54:02.179299: I tensorflow/core/kernels/data/tf_record_dataset_op.cc:370] TFRecordDataset `buffer_size` is unspecified, default to 262144


tf.Tensor(1597132139, shape=(), dtype=int64)


2025-01-31 20:54:02.693244: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: OUT_OF_RANGE: End of sequence


In [5]:
import TensorSlider

In [6]:
WS = TensorSlider.WindowSlider(30, 10, dataset1m, {"5m": dataset5m})
WS2 = TensorSlider.WindowSlider(30, 10, dataset1m)

In [7]:
for time in WS:
    print(time)
    break
for time in WS2:
    print(time)
    break

[<tf.Tensor: shape=(2, 5, 30), dtype=float64, numpy=
array([[[1.17202002e+04, 1.17287998e+04, 1.17265996e+04, 1.17297002e+04,
         1.17254004e+04, 1.17267998e+04, 1.17187998e+04, 1.17167002e+04,
         1.17119004e+04, 1.17170996e+04, 1.17320996e+04, 1.17089004e+04,
         1.16690996e+04, 1.16907002e+04, 1.16850996e+04, 1.16962002e+04,
         1.16825996e+04, 1.16925000e+04, 1.16847002e+04, 1.16827002e+04,
         1.16590000e+04, 1.17007998e+04, 1.16827002e+04, 1.16887998e+04,
         1.16904004e+04, 1.16992998e+04, 1.17024004e+04, 1.17024004e+04,
         1.17090000e+04, 1.17080996e+04],
        [1.17292002e+04, 1.17305000e+04, 1.17284004e+04, 1.17297002e+04,
         1.17254004e+04, 1.17274004e+04, 1.17187998e+04, 1.17167002e+04,
         1.17170996e+04, 1.17287002e+04, 1.17329004e+04, 1.17089004e+04,
         1.16932002e+04, 1.16949004e+04, 1.16964004e+04, 1.16962002e+04,
         1.16922998e+04, 1.16927002e+04, 1.16872002e+04, 1.16827002e+04,
         1.16962998e+04, 1.17

In [17]:
#iterate = WS.__iter__()

for i in range(1):
    next = iterate.__next__()


In [18]:
print(next[1])

tf.Tensor(
[11714.4 11715.3 11719.1 11728.7 11731.  11728.9 11731.  11728.2 11724.6
 11704.  11718. ], shape=(11,), dtype=float32)
